server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cycle
    password: "&*531cW9/?"
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cycleuop@gmail.com
    password: rtwo vani qyiy kbgj
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "257276141541-av8vs5jp5u7e9f3am8dllo761kg7abo8.apps.googleusercontent.com"
            client-secret: "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"
#            scope:
#              - openid
#              - profile
#              - email
#              - https://www.googleapis.com/auth/calendar.events
#
#        provider:
#          google:
#              authorization-uri: https://accounts.google.com/o/oauth2/auth
#              token-uri: https://accounts.google.com/o/oauth2/token
#              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#              user-name-attribute: sub
#              jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  servlet:
    multipart:
      max-file-size: 100MB   # Increase size for large files
      max-request-size: 100MB # Increase size for large files

  tomcat:
    max-http-header-size: 16384 # Adjust if needed for large headers
    max-swallow-size: 104857600 # 100MB, adjust according to file size needs
